language: ruby
rvm:
- 2.6.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: p1+DiM7eMgcxiStTeC+KqborySBr2B2qefpD8wDwsxSxMQbKHHRicS2dEFHqug7Bgz8ZqBdnSDo4K9/pJhVu4sCIwc6o+nVr1vMgoDEHkh/oA56n5lEqQp2s+Dz76GWJf2Vvgtw6qq910OBJzlYLPcOQ3Cz9ep1xMLfbmgotVKpPKIH/umYtRdEX9WiGmg+3Nk/t5dddQ0DxC11WE2FqEQMntIO5zTZ3/6/rhh2yI7dNZj4Yq4VTbwqjFwJVmaM7r56tmGejjBn2M/4BnpoQ0+DfGjC/8PMRXA1tVDa4xSUTVoiQ7FW0djeJoY4uHVOaHO3f7oO6YTl3red86zN3r3nRg6jcrfAOEJu6CRzITBvHgbO7FPAUpn83rQjmQHf1BY3saZ9bTDwVv3MIVi2Rc1wsSguyH6SDBvyaL2rMY3vPffNEX50QjWF1+gjNxHYDLsfCa2Ieq8mLpH0LcjVztW1ZiAdpmC4Xs7pOCsF4AyvB61jEbBXv69HzU9cEBSMSKYhs4nd9YG5hVpPxXF+qwgSa5ZQhtQcHMmq8b+rEXzLr7It+Y7Bvg3kc0i4qsgDEHN164ilNRzbL5P7MHVNGFcYofPjFXU5uvQgjTGMdi5Jdz/A6THQRNgn4aapcHtKyPRTF1h/5qiLJR/A5MeOFRg+rBIr1eZIlcjX69QBnc9k=
