language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: FtmqWzqZxGkYRhDJiU8xpI1byB0xtcTP/DY+1O5j8tnrqVoT1wE3SNiRHYGQUIcjCJxy7Uh8mibgNCYP/US0DGnw3032Re5p+dr99gUo6kgr09eLGZ3z/yD6WYwxeK32M6IUB0SWZLD+a5XwsrNo2FJYUekE7RKNPCEjDKa4Dnr5E05lNZHr1imNDi7/yuyz/q0YQDVIqX6jnKfcE7/HMfPb9j0BOIXTRpjoioRkeGPK1ADvHHrNcgxUQvJsqldBXFrDLmAmQZgDg76P6uA0dLCQQ88FydusyY7x7sBfGK7awyoK+vTWtNuHgYeTl5x6K201vQGX9v9E+AkL5bSvwsUacGOgEpo7NGYppAPTN7G/BSo9ZlAMfvspdKJe02mgGHnmT7O9UN0PBAinPaHTWcb5ORh/wOFa6IAwT3ShCYc8xHmnwTPxT4RpU5IaCWvrF5Ya6ES4OKAjmFNpuIFYExFfbV6D9LS2yI5ZEsA5BEl5Ye8MGXK8NMvVlTWSy6pEw+idX1pgcyqOmvvaY+OhjA0Z/UOV4zuhdN0JLcR5U+PQWrZveyhAsg1AC/vv0oELao6P8o7CbBvjE8UYQuQCfASVeTXKtbOEIDTcf0pYoCUwvxla2KgdvFWC23m6kKfLMLZVoxsnLvrJvbZPKd50y7ocy0RkRq7Tx2h5VyNxjXE=
