= Projet : envoyer des données au _device_
:showtitle:
:page-navtitle: Lorawan Entry
:page-root: ../../../

[TIP]
.Objectif
====
Envoyer des données au noeud LoRaWAN (ici un Feather M0) et les traiter (allumer une LED qui peut symboliser un relais ou tout autre composant)
====

Comme pour l'émission (_uplink_) et le traitement de données depuis l'objet, l'envoi de données vers l'objet (_downlink_) est défini par le protocole LoRaWAN.

Lorsque l'objet envoie des données, toutes les passerelles à proximité reçoivent le paquet et le transmettent au serveur de réseau (loraserver). Celui-ci choisit alors le paquet de la passerelle la mieux placée notamment sur la base de la qualité de la liaison radio avec l'objet.

Une fois que l'objet a reçu un accusé de réception de la passerelle la mieux placée, il attend durant deux fenêtres temporelles (_RX Windows_) l’éventuelle réception d'un message (_downlink message_).

[TIP]
=====
Le première fenêtre dure 1s et la seconde 2s. Durant ces (_RX Windows_), l'objet attend une info indiquant que des données sont dans la file d'attente pour être transmises. Si c'est la cas, la fenêtre sera prolongé le temps nécessaire (maximum 3s). Tout cela est défini dans le protocole. Pour info, il y a deux fenêtres de _join_ une de 5s et l'autre de 6s.
=====

De son côté, le serveur de réseau, une fois l'accusé de réception envoyé via la passerelle, regarde s'il n'y a pas des messages à envoyer dans le file d'attente de l'objet. Si oui, il les transmet à la passerelle qui va utiliser une des fenêtres temporelles durant lesquelles l'objet écoute.

La réception effective des données par l'objet n'est donc pas immédiate. Ce n'est pas une limitation mais une fonctionnalité du protocole. Rappelons qu'il est destiné à des réseaux longue portée, bas débit et surtout basse consommation. Si cela ne correspond pas à vos besoins, voir du côté du Wifi, Bluetooth, zigbee...



[CAUTION]
.Pour les utilisateurs avec un compte sur les serveurs
====

 ssh root@loraserver.tetaneutral.net -p2222

Comme loraserver est dans un container docker, il n'y rien dans `/etc/var/log`. Pour voir en temps réel les 30 derniers messages de log du loraserver :

 docker logs --tail 30 -f loraserverdocker_loraserver_1

Plus d'infos ici : https://docs.docker.com/engine/reference/commandline/logs/

 docker logs --tail 40 -f loraserverdocker_appserver_1
====

== Envoyer des données via MQTT

Selon la https://www.loraserver.io/lora-app-server/integrate/data/[documentation], il suffit de publier sur le topic : `application/[applicationID]/device/[devEUI]/tx`

avec une payload du type suivant :

[source,]
----
{
    "reference": "abcd1234",                  // reference which will be used on ack or error (this can be a random string)
    "confirmed": true,                        // whether the payload must be sent as confirmed data down or not
    "fPort": 10,                              // FPort to use (must be > 0)
    "data": "...."                            // base64 encoded data (plaintext, will be encrypted by LoRa Server)
    "object": {                               // decoded object (when application coded has been configured)
        "temperatureSensor": {"1": 25},       // when providing the 'object', you can omit 'data'
        "humiditySensor": {"1": 32}
    }
}
----

Voici un exemple de payload. Ici nous envoyons 1 codé en base 64 :

[source,json]
.fichier testpayload
----
{
    "reference": "abcd1234",
    "confirmed": true,
    "fPort": 10,
    "data": "MQo="
}
----

et pour l'envoyer à l'objet :

 mosquitto_pub -h loraserver.tetaneutral.net -t "application/5/device/010203040506070b/tx" -f testpayload

pour encoder un texte en base 64 faire :

 echo "texte" | base64

[TIP]
====
On peut aussi utiliser l'API de loraserver : https://www.loraserver.io/lora-app-server/integrate/api/

TODO...
====

== Traiter les données reçues

Dans l'automate LMIC, on peut rajouter l'appel à une fonction que l'on nommera, par exemple, `do_if_data_received()`.

[source,c]
----
case EV_TXCOMPLETE:
    Serial.println(F("EV_TXCOMPLETE (includes waiting for RX windows)"));
    if (LMIC.txrxFlags & TXRX_ACK)
        Serial.println(F("Received ack"));
    if (LMIC.dataLen)
    {
        Serial.println(F("Received "));
        Serial.println(LMIC.dataLen);
        Serial.println(F(" bytes of payload"));
        do_if_data_received();
    }
----

Les données reçues sont stockées dans un tableau d'entiers non signés de type `u1_t` (en fait de type `uint8_t`) d'une longueur maximum de 64 bits nommé `LMIC.frame` (voir ligne 250 du fichier `lmic.h`).

Le source de `do_if_data_received()` peut être :

[source,c]
----
void do_if_data_received()
{
    for (int i = 0; i < LMIC.dataLen; i++)
    {
        if (LMIC.frame[LMIC.dataBeg + i] < 0x10)
        {
            Serial.print(F("0"));
        }
        Serial.write(LMIC.frame[LMIC.dataBeg + i]);
    }
    Serial.println("");
    if (LMIC.frame[LMIC.dataBeg] == 49) // FIXME: pas très heureux...
    {
        digitalWrite(13, HIGH);
    }
    else
    {
        digitalWrite(13, LOW);
    }
}
----

== Source complet

[source,c]
----
include::./src/FeatherM0-LoRaWAN-exemple-downlink/src/main.cpp[]
----
